manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: flumelabs
      url-base: https://github.com/flumelabs
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.1
      import: app/west.yml
    - name: zmk-canvas-shield
      remote: flumelabs
      revision: main
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-tri-state
      remote: urob
      revision: v0.1
  self:
    path: config